export interface Finding {
  sev: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW' | 'INFO'
  id: string
  title: string
  summary: string              // summary + description, with inline `code` references
  rootCause: string            // mandatory inline `code` references
  symmetry?: string            // only present when an asymmetric paired-function bug applies
  externalPreconditions: string   // markdown, bullet list of conditions outside the protocol's control
  internalPreconditions: string   // markdown, bullet list of protocol-state conditions required
  attackPath: string           // numbered step list
  impact: string
  poc: string                  // runnable PoC code block + expected log output
  mitigation: string
  prob: string[]
  aave: string[]
  swc: string[]
  immunefi?: string[]          // matched real-world Immunefi bounty precedents, e.g. "Enzyme — price oracle manipulation ($19K)"
  fizzProperties?: string[]    // Echidna/Medusa-compatible invariant property one-liners generated by the Fizz skill
  pocValidationError?: string  // populated if the PoC fails a pre-submission compile/run check
  confidence?: number
  lens?: string
}

export interface Lead {
  title: string
  codeSmells: string
  description: string
}

export interface SoloditRef {
  title: string
  severity: string
  firm: string
  protocol: string
  tags: string[]
  sourceLink: string
}

export interface ProbModel {
  id: string
  name: string
  icon: string
  desc: string
  formula: string
  apps: string[]
  risks: string[]
  aave: string
}

export interface AaveSection {
  section: string
  items: { t: string; w: string }[]
}

export interface VulnRow {
  n: string; s: 'High' | 'Medium' | 'Low'; swc: string; dasp: string
  prob: string; aave: string; det: string
  precedent?: string   // matched real-world Immunefi bounty precedent, "Protocol — pattern (bounty)"
  solodit?: boolean    // true when this row's pattern is one of the live Solodit corroboration search terms (see RISK_KEYWORDS in api.audit.ts)
}

export const PROB_MODELS: ProbModel[] = [
  { id:'markov', name:'Markov Chain', icon:'🔄', desc:'State-based probability transitions', formula:'P(X_t+1|X_t)',
    apps:['Lending: Healthy→At-Risk→Liquidatable','Bridge validator consensus states','User: depositor→borrower→liquidated'],
    risks:['Cascading liquidations exploiting state gaps','Privilege escalation through unexpected paths'],
    aave:'HF state machine: HF>1 → HF~1 → HF<0.95 → 100% liquidation (V3 variable close factor)' },
  { id:'bayesian', name:'Bayesian Inference', icon:'🔮', desc:'Prior updated with on-chain evidence', formula:'P(A|B)=P(B|A)·P(A)/P(B)',
    apps:['Dynamic risk scoring per tx pattern','Oracle reputation scoring','Cross-chain fraud detection'],
    risks:['Prior manipulation via synthetic tx history','False positive flood disabling monitors'],
    aave:'Risk Admin updates: weight by historical protocol behavior before applying' },
  { id:'poisson', name:'Poisson Process', icon:'📊', desc:'Discrete events over time intervals', formula:'P(X=k)=(λ^k·e^-λ)/k!',
    apps:['Oracle price update clustering','Flash loan timing windows','Liquidation event bursts'],
    risks:['MEV bot clustering DoS','Congestion attacks during volatility'],
    aave:'Liquidation bursts: λ spikes 10x during market crashes → keeper gas exhaustion' },
  { id:'lognormal', name:'Log-Normal', icon:'💹', desc:'Right-skewed — models collateral price tails', formula:'f(x)=e^-(ln x-μ)²/2σ²',
    apps:['Token price 3σ black swan events','Collateral ratio distributions','TVL growth and impermanent loss'],
    risks:['3σ drop pushes HF from 1.5 to <1 in one block','Asymmetric liquidation cascades'],
    aave:'E-Mode: stablecoin depeg at 3σ triggers correlated liquidations across category' },
  { id:'beta', name:'Beta Distribution', icon:'🎯', desc:'Bounded [0,1] — ratios and utilization rates', formula:'f(x)=x^(α-1)(1-x)^(β-1)/B(α,β)',
    apps:['Pool utilization approaching 100%','Collateralization ratios near LT','Governance voting participation'],
    risks:['Utilization→1.0 triggers liquidity crisis','Collateral ratio→LT causes mass liquidation'],
    aave:'Beta model: utilization→100% triggers slope2 rate spike → repayment DoS' },
  { id:'game_theory', name:'Game Theory', icon:'♟️', desc:'Nash equilibrium and attack incentive analysis', formula:'u_i(s_i*,s_-i*)≥u_i(s_i,s_-i*)',
    apps:['MEV extraction profitability','Governance vote-buying dynamics','Liquidation keeper incentives'],
    risks:['Liquidation bonus < gas cost → no liquidators → bad debt','Tragedy of the commons'],
    aave:'Liquidation bonus must exceed gas+opportunity cost or rational keepers abstain' },
  { id:'monte_carlo', name:'Monte Carlo', icon:'🎰', desc:'Multi-scenario stress testing via random sampling', formula:'θ̂=(1/N)·Σf(X_i)',
    apps:['Liquidation probability under 1000 scenarios','Bridge security stress testing','Protocol revenue forecasting'],
    risks:['Correlated failures only found under compound scenarios'],
    aave:'Simulate 10k scenarios: probability distribution of HF<1 events given current positions' },
  { id:'copula', name:'Copula Models', icon:'🔗', desc:'Multi-asset dependency and contagion', formula:'C(u₁,u₂,...,uₙ)',
    apps:['Correlated asset liquidation cascades','Cross-protocol systemic risk','LP pair correlation under stress'],
    risks:['USDC depeg triggers simultaneous liquidations across all E-Mode positions'],
    aave:'E-Mode stablecoin: near-1 correlation → single depeg = mass liquidation' },
  { id:'weibull', name:'Weibull Distribution', icon:'⚙️', desc:'Time-varying failure rate (bathtub curve)', formula:'f(x)=(k/λ)(x/λ)^(k-1)e^-(x/λ)^k',
    apps:['Contract vulnerability discovery rate over time','Bridge validator reliability','Upgrade failure probability'],
    risks:['Highest bug density in first 30 days post-deploy'],
    aave:'New reserve listing: highest exploit probability in first 30 days → conservative debt ceiling' },
  { id:'exponential', name:'Exponential', icon:'📉', desc:'Time between events — memoryless property', formula:'f(x)=λ·e^-λx',
    apps:['Oracle heartbeat staleness windows','Flash loan opportunity intervals','Governance proposal timing'],
    risks:['Staleness exploitation during long update gaps'],
    aave:'Chainlink: ETH/USD 1hr, BTC/USD 24hr → model staleness exploitation windows' },
  { id:'normal', name:'Normal / Gaussian', icon:'📈', desc:'Symmetric — gas prices and slippage', formula:'f(x)=e^-(x-μ)²/2σ²/σ√2π',
    apps:['Gas price prediction and keeper budget','AMM slippage estimation','APY fluctuation modeling'],
    risks:['3σ gas spike exceeds liquidation keeper budget'],
    aave:'Keeper budget must cover 99.9th percentile gas spike or all liquidations fail' },
  { id:'pareto', name:'Pareto / Power Law', icon:'👑', desc:'80/20 rule — heavy-tailed concentration', formula:'f(x)=α·x_m^α/x^(α+1)',
    apps:['Whale wallet concentration','TVL concentration by top holders','Validator stake distribution'],
    risks:['Governance: top 3 holders control outcome'],
    aave:'aToken Pareto: if top 5 wallets hold >50% → bank run risk elevated' },
  { id:'geometric', name:'Geometric', icon:'⏱️', desc:'Time to first success across repeated trials', formula:'P(X=k)=(1-p)^(k-1)·p',
    apps:['Blocks until arbitrage opportunity','Time to liquidation threshold','Validator slashing timing'],
    risks:['Expected time to profitable exploit determines attack feasibility'],
    aave:'Expected blocks until 95% utilization → interest spike attack window' },
  { id:'binomial', name:'Binomial', icon:'🎲', desc:'Binary outcomes across n independent trials', formula:'P(X=k)=C(n,k)p^k(1-p)^(n-k)',
    apps:['Multi-sig approval probability','Bridge relay confirmation rates','Validator success rates'],
    risks:['5-of-9 with p=0.25 per key → P(5+ compromised)=8.7% annually'],
    aave:'Governance quorum: binomial model of participation probability' },
  { id:'queueing', name:'Queueing Theory', icon:'⏳', desc:'Transaction ordering and mempool dynamics', formula:"L=λW (Little's Law)",
    apps:['Mempool tx queue dynamics','Bridge message ordering','Oracle queue under load'],
    risks:['Frontrunning via priority gas auction','Queue flooding DoS'],
    aave:'L2 sequencer restart: all queued liquidations execute simultaneously' },
  { id:'kalman', name:'Kalman Filter', icon:'📡', desc:'Recursive state estimation — fuses expected state transitions with observed deviations across a call sequence', formula:'x̂ₖ = Fx̂ₖ₋₁ + K(zₖ − Hx̂ₖ₋₁)',
    apps:['Multi-call balance/share drift detection','Sequential state-invariant tracking across a tx sequence','Fuzzing-seed prioritization where uncertainty grows fastest'],
    risks:['Single-call deviation looks bounded but compounds across repeated calls into material drain','Growing residual across a call sequence flags reentrancy or accounting drift a single-tx check misses'],
    aave:'Interest/index accrual: per-call rounding that individually looks like dust but compounds across many calls into share-price manipulation' },
  { id:'hmm', name:'Hidden Markov Model', icon:'🕳️', desc:'Regime detection — classifies each function into a hidden risk state from observable code features, then weighs transitions between states', formula:'P(qₜ|qₜ₋₁)·P(oₜ|qₜ)',
    apps:['Per-function risk-regime classification (safe / reentrancy-prone / arithmetic-risk / access-control-risk / complex-multi-effect)','Call-graph transition risk — a risky-regime function calling into another risky-regime function','File-relative outlier detection — the one function that doesn\'t match its siblings\' feature profile','Prioritizing which functions get the deepest lens pass first'],
    risks:['A function that looks safe in isolation but sits in a call chain of risky-regime functions inherits compounded risk the sweep would miss function-by-function','High external-call ratio + low access-control score + high loop complexity co-occurring is a stronger signal than any one feature alone','A function that is only an outlier relative to its own file\'s other functions — not any absolute threshold — is where hand-rolled helpers hide unreviewed logic'],
    aave:'Flash-loan receiver + liquidation path: classify as high-risk regime when external-call ratio and value-transfer frequency are both elevated in the same function' },
]

export const AAVE_CHECKLIST: AaveSection[] = [
  { section: 'V2 — Core Architecture', items: [
    { t: 'LendingPool, CollateralManager logic libraries version-locked', w: 'Prevents unintended upgrades during forks' },
    { t: 'ValidationLogic / GenericLogic / ReserveLogic consistently applied', w: 'Ensures consistent validation across all operations' },
    { t: 'DebtTokens and aTokens minted/burned 1:1 with underlying', w: 'Prevents accounting mismatches' },
    { t: 'Protocol parameters managed via time-locked Configurator or multisig', w: 'Prevents admin privilege abuse' },
  ]},
  { section: 'V2 — Deposits & Withdrawals', items: [
    { t: 'validateDeposit confirms reserves active and not frozen', w: 'Prevents deposits into inactive assets' },
    { t: 'updateState() recomputes liquidity and borrow indices atomically', w: 'Avoids stale index rate calculation errors' },
    { t: 'validateWithdraw re-evaluates HF via balanceDecreaseAllowed()', w: 'Prevents health-factor-reducing withdrawals' },
    { t: 'Dust handled correctly on full withdrawals', w: 'Prevents collateral lockup via precision flags' },
    { t: 'Withdrawals follow CEI pattern before token transfers', w: 'Reduces reentrancy risk' },
  ]},
  { section: 'V2 — Borrowing & Interest', items: [
    { t: 'Both stable and variable debt modes validated before minting', w: 'Ensures rate model consistency' },
    { t: 'validateBorrow() enforces LTV and HF using current oracle prices', w: 'Prevents borrow on stale prices' },
    { t: 'repay() burns exact type/amount of debt tokens', w: 'Maintains debt state integrity' },
    { t: 'Slope1, Slope2 and utilization breakpoints tested per asset', w: 'Misconfigured curves freeze liquidity' },
    { t: 'InterestRateStrategy interface compatible across networks', w: 'Avoids cross-chain lending pool failures' },
  ]},
  { section: 'V2 — Liquidations', items: [
    { t: 'Liquidation threshold max 50% debt in Aave V2', w: 'Keeps liquidation math within safe limits' },
    { t: 'Pool.getUserAccountData(address) used for HF and collateral data', w: 'Accurate liquidation metrics' },
    { t: 'debtToCover = uint(-1) only when full liquidation desired', w: 'Avoids over-liquidation' },
    { t: 'State updates precede token transfers in liquidation flow', w: 'Prevents reserve manipulation during liquidation' },
  ]},
  { section: 'V2 — Flash Loans', items: [
    { t: 'validateFlashLoan() verifies repayment + premium', w: 'Prevents fee bypass exploits' },
    { t: 'executeOperation callbacks sandboxed against reentrancy', w: 'Avoids reentrancy during flash loan execution' },
    { t: 'Empty market rounding errors tested (cumulateToLiquidityIndex)', w: 'Empty pool rounding can cause balance inflation' },
    { t: 'Protocol mints aToken on every new market initialization', w: 'Prevents manipulation of empty pools' },
  ]},
  { section: 'V3 — E-Mode', items: [
    { t: 'Asset correlation confirmed before enabling E-Mode category', w: 'Prevents liquidation cascades from miscorrelation' },
    { t: 'setUserEMode(id) reverts safely if HF<1 or unsupported tokens borrowed', w: 'Prevents unsafe E-Mode transitions' },
    { t: 'Category id=0 used to disable E-Mode safely', w: 'Ensures clean exit from efficiency mode' },
    { t: 'E-Mode LTV/LT higher than default non-E-Mode params per asset', w: 'E-Mode asset addition invariant from tech paper' },
  ]},
  { section: 'V3 — Isolation Mode', items: [
    { t: 'Debt ceiling bits 212-251 decoded from Pool.getConfiguration(asset)', w: 'Misreading config allows excessive borrowing' },
    { t: 'Only governance-approved stablecoins borrowable in isolation', w: 'Prevents volatile asset bypass of isolation limits' },
    { t: 'Isolated and non-isolated positions never mixed', w: 'Mixing invalidates debt ceiling enforcement' },
    { t: 'checkNoSuppliers() enforced when adding isolated asset', w: 'Isolation mode invariant from V3 tech paper' },
  ]},
  { section: 'V3 — Liquidations (Variable Close Factor)', items: [
    { t: 'HF ≤ 0.95 → 100% liquidation; HF > 0.95 → 50% max', w: 'Matches Aave V3 variable close factor spec' },
    { t: 'L1: Pool.liquidationCall(), L2: L2Pool.liquidationCall()', w: 'Prevents integration errors between layers' },
    { t: 'Price Oracle Sentinel grace period respected on L2 sequencer downtime', w: 'Prevents unfair liquidations on sequencer restart' },
  ]},
]

export const VULN_MATRIX: VulnRow[] = [
  { n:'Reentrancy (ETH)', s:'High', swc:'SWC-107', dasp:'DASP-1', prob:'Markov', aave:'Flash loan callbacks, liquidation hooks', det:'Slither, manual CEI review', precedent:'O3 Swap — ERC-777 callback reenters unprotected swap ($500)', solodit:true },
  { n:'Controlled Delegatecall', s:'High', swc:'SWC-112', dasp:'DASP-2', prob:'Game Theory', aave:'Proxy upgrades, POOL_ADMIN role', det:'Static analysis', solodit:true },
  { n:'Arbitrary Send', s:'High', swc:'SWC-105', dasp:'DASP-2', prob:'Poisson', aave:'aToken minting paths', det:'Slither arbitrary-send', precedent:'Zapper — arbitrary calldata forwarded to unvalidated target ($25K)' },
  { n:'Transaction Ordering (TOD)', s:'High', swc:'SWC-114', dasp:'DASP-7', prob:'Queueing', aave:'Oracle price update vs borrow race', det:'Mempool analysis' },
  { n:'Uninitialized State', s:'High', swc:'SWC-109', dasp:'-', prob:'Weibull', aave:'Proxy implementation slots', det:'Slither, init() checks', precedent:'Wormhole — uninitialized proxy, attacker calls initialize() ($10M)', solodit:true },
  { n:'Oracle Manipulation', s:'High', swc:'SWC-116', dasp:'DASP-8', prob:'Exponential+Poisson', aave:'Chainlink staleness, slot0 price', det:'latestAnswer() audit', precedent:'Enzyme Finance — single-tx price oracle manipulation ($19K)', solodit:true },
  { n:'Flash Loan Attack', s:'High', swc:'-', dasp:'-', prob:'Poisson+Monte Carlo', aave:'Price oracle manipulation window', det:'Economic attack modeling', precedent:'Fei Protocol — flash-loan-atomic accounting manipulation ($800K)', solodit:true },
  { n:'Read-Only Reentrancy', s:'High', swc:'SWC-107', dasp:'DASP-1', prob:'Markov', aave:'Balancer totalSupply during callback', det:'Manual view function audit', solodit:true },
  { n:'Signature Replay', s:'High', swc:'SWC-121', dasp:'-', prob:'Geometric', aave:'Credit delegation, permit()', det:'nonce+chainId audit', solodit:true },
  { n:'Missing Access Control', s:'High', swc:'SWC-105', dasp:'-', prob:'Game Theory', aave:'RISK_ADMIN: LT set to 0', det:'Role assignment audit', precedent:'Enzyme Finance — sibling function missing privilege check ($400K) · iop-paradex — operator unauthorized fund transfers (Critical, Immunefi Bounty Boost)', solodit:true },
  { n:'Integer Overflow', s:'Medium', swc:'SWC-101', dasp:'DASP-3', prob:'Normal', aave:'Interest accrual arithmetic', det:'Slither, 0.8+ check' },
  { n:'Unchecked Low-Level Call', s:'Medium', swc:'SWC-104', dasp:'DASP-4', prob:'Binomial', aave:'Flash loan return value', det:'Slither unchecked-lowlevel', precedent:'RAI — trusted external-call return-data size, griefing DoS' },
  { n:'tx.origin Auth', s:'Medium', swc:'SWC-115', dasp:'DASP-2', prob:'Game Theory', aave:'Liquidation caller checks', det:'tx.origin grep' },
  { n:'Incorrect Equality', s:'Medium', swc:'SWC-132', dasp:'DASP-5', prob:'Bayesian', aave:'utilization == 100% check', det:'== vs >= audit' },
  { n:'ERC20 Non-Conformance', s:'Medium', swc:'-', dasp:'-', prob:'Bayesian', aave:'Fee-on-transfer tokens in reserves', det:'erc-interface-scanner' },
  { n:'Price Manipulation (AMM)', s:'High', swc:'-', dasp:'-', prob:'Log-Normal+Monte Carlo', aave:'slot0 price used as oracle', det:'TWAP vs spot audit', precedent:'Raydium — concentrated-liquidity tick manipulation ($505K)' },
  { n:'Precision Loss / Rounding', s:'Medium', swc:'SWC-101', dasp:'-', prob:'Beta+Normal', aave:'Share inflation on empty market', det:'Division order review', precedent:'Balancer — pool-math rounding error, compounds over swaps ($1M)' },
  { n:'Fee-on-Transfer Token', s:'Medium', swc:'-', dasp:'-', prob:'Bayesian', aave:'validateDeposit: credited > received', det:'balance-before/after' },
  { n:'Timestamp Dependence', s:'Low', swc:'SWC-116', dasp:'DASP-8', prob:'Exponential', aave:'Interest accrual block.timestamp', det:'Slither timestamp' },
  { n:'Costly Loop', s:'Low', swc:'SWC-128', dasp:'DASP-5', prob:'Queueing', aave:'Reserve list iteration gas', det:'Slither costly-loop', precedent:'Stacks — unbounded loop locks a shared resource (~$76K)' },
  { n:'Calls in Loop', s:'Low', swc:'SWC-113', dasp:'DASP-5', prob:'Queueing', aave:'Multi-asset HF calculation', det:'Slither calls-loop' },
  { n:'Controlled Array Length', s:'High', swc:'-', dasp:'-', prob:'Poisson', aave:'Reserve list DoS', det:'Manual: unbounded loops' },
  { n:'Suicidal Contract', s:'High', swc:'SWC-106', dasp:'DASP-2', prob:'Game Theory', aave:'Emergency Admin selfdestruct', det:'selfdestruct grep', solodit:true },
  { n:'Locked Ether', s:'Medium', swc:'-', dasp:'DASP-5', prob:'Beta', aave:'aToken ETH wrapping', det:'Slither locked-ether' },
  { n:'Block Parameter Dependence', s:'Low', swc:'SWC-116', dasp:'DASP-6', prob:'Poisson', aave:'block.number for time assumptions', det:'Slither block-other' },
  { n:'Unchecked Send', s:'Medium', swc:'SWC-104', dasp:'DASP-4', prob:'Binomial', aave:'aToken ETH transfer', det:'Slither unchecked-send' },
  { n:'Parity Multisig Bug', s:'High', swc:'-', dasp:'-', prob:'Binomial', aave:'ACL_ADMIN role hijack', det:'Manual role audit' },
  { n:'Flash Loan Price Manip', s:'High', swc:'-', dasp:'-', prob:'Copula+Monte Carlo', aave:'Correlated collateral crash', det:'Economic stress test' },
  { n:'Uninitialized Proxy Re-Init', s:'High', swc:'SWC-109', dasp:'-', prob:'Weibull', aave:'Upgradeable pool/reserve implementations', det:'initializer/_disableInitializers audit', precedent:'88mph — initializer re-callable post-deploy ($42K)', solodit:true },
  { n:'Infinite Mint / Duplicated Spend', s:'High', swc:'-', dasp:'-', prob:'Binomial', aave:'aToken mint/burn 1:1 invariant', det:'Manual accounting-delta audit', precedent:'Aurora — infinite spend ($6M) · Optimism — money duplication ($2M)', solodit:true },
  { n:'Double-Counted Collateral', s:'High', swc:'-', dasp:'-', prob:'Bayesian', aave:'Free-collateral / HF double-accounting', det:'Cross-path accounting reconciliation', precedent:'Notional Finance — free collateral double-counted across two paths ($1.1M)' },
  { n:'Delegation/Permission Check Error', s:'Medium', swc:'SWC-105', dasp:'-', prob:'Game Theory', aave:'Credit delegation account reference', det:'Delegate/allowance mapping audit', precedent:'APWine — delegation check used wrong account reference ($100K)' },
  { n:'Consensus/Quorum Bypass', s:'High', swc:'-', dasp:'-', prob:'Game Theory', aave:'Validator/keeper consensus paths', det:'Threshold-check audit', precedent:'Polygon — consensus bypass ($75K)' },
  { n:'Cross-Chain Message Spoofing', s:'High', swc:'-', dasp:'-', prob:'Binomial+Weibull', aave:'Bridge role message verification', det:'Message-signature/relay audit', precedent:'Scroll — bridge message verification gap ($1M)' },
  { n:'Insufficient ZK Proof Verification', s:'High', swc:'-', dasp:'-', prob:'Copula Models', aave:'-', det:'Proof-circuit boundary audit', precedent:'zkSync — insufficient proof verification ($200K)' },
  { n:'Logic-Error Accounting Drain', s:'High', swc:'SWC-101', dasp:'-', prob:'Kalman Filter+Hidden Markov Model', aave:'Strategy/vault share accounting', det:'Compounding-drift + regime-transition audit', precedent:'Belt Finance ($1.05M) · Port Finance ($630K) · Mushrooms Finance ($60K)', solodit:true },
  { n:'Privileged Callback Missing Guard (Keeper/Poke)', s:'High', swc:'SWC-105', dasp:'-', prob:'Hidden Markov Model', aave:'Reward-distribution keeper functions', det:'Access-control-regime audit on public callbacks', precedent:'Alchemix — unguarded voterPoke() enables infinite FLUX mint (Critical, Immunefi Bounty Boost)' },
  { n:'Withdrawal Accounting Desync', s:'High', swc:'SWC-101', dasp:'-', prob:'Kalman Filter', aave:'Withdraw/redeem share-vs-total updates', det:'Cross-variable update audit on withdraw path', precedent:'Alchemix — withdraw() omits totalVoting update, corrupting downstream accounting (Critical, Immunefi Bounty Boost)' },
  { n:'Slippage Formula Miscomputed (not just missing)', s:'High', swc:'SWC-114', dasp:'-', prob:'Game Theory', aave:'Swap/redeem minOut calculation', det:'Formula-level slippage audit, not just presence check', precedent:'Alchemix — "slippage protection is inaccurate" (Critical, Immunefi Bounty Boost)' },
  { n:'Burn/Redeem Underflow Freezes Funds', s:'Medium', swc:'SWC-101', dasp:'DASP-3', prob:'Normal / Gaussian', aave:'Debt token burn precision', det:'Underflow-path audit on burn()', precedent:'folks-liquid-staking — underflow in burn() partially freezes user funds (High, Immunefi Bounty Boost)' },
  { n:'Input Validation Gap on State-Changing Entry Point', s:'High', swc:'SWC-123', dasp:'DASP-5', prob:'Bayesian Inference', aave:'Deposit/issuance entry-point parameter checks', det:'Entry-point parameter-boundary audit', precedent:'circuitdaoiop — missing validation in coin-issuance lets attacker issue arbitrary amounts (Critical, Immunefi Bounty Boost)' },
]

export const DEMO_FINDINGS: Record<string, Finding[]> = {
  lending: [
    { sev:'CRITICAL', id:'CRIT-01', title:'Division-by-zero DoS when totalShares = 0',
      summary:'`liquidate()` computes `bonus = collateral * BONUS / totalShares` before validating `totalShares > 0`. A flash-loan-funded withdrawal can drain the pool to zero shares, after which every call to `liquidate()` reverts on division by zero — permanently.',
      rootCause:'`totalShares` is read as the divisor in `liquidate()` with no `require(totalShares > 0)` guard, and no minimum-share floor is enforced on the last withdrawal.',
      externalPreconditions:'- Attacker has access to a flash loan large enough to cover the pool\'s full liquidity.',
      internalPreconditions:'- `totalShares` must be reducible to exactly 0 through normal `withdraw()` calls (no minimum-liquidity lock on the pool).',
      attackPath:'1. Attacker flash-borrows the full pool liquidity.\n2. Attacker withdraws their full share, driving `totalShares` to 0.\n3. Attacker calls `liquidate(victim)`.\n4. `bonus = collateral * BONUS / totalShares` reverts (division by zero).\n5. Every subsequent `liquidate()` call reverts identically — the liquidation engine is permanently DoS\'d.',
      impact:'Permanent denial of service on the liquidation engine. All underwater positions accumulate unbounded bad debt with no recovery path short of a contract upgrade.',
      poc:'```solidity\nfunction test_liquidationDosViaZeroShares() public {\n    // pool starts with normal liquidity\n    vm.startPrank(attacker);\n    flashLoan.borrow(pool.totalLiquidity());\n    pool.withdraw(pool.balanceOf(attacker)); // totalShares -> 0\n\n    vm.expectRevert(); // division by zero\n    pool.liquidate(victim);\n    vm.stopPrank();\n}\n```\nExpected log output:\n```\n[FAIL: panic: division or modulo by zero (0x12)] test_liquidationDosViaZeroShares()\n```',
      mitigation:'Add `require(totalShares > 0, "Empty pool")` before the bonus calculation, and lock a `MINIMUM_LIQUIDITY` floor on pool initialization so `totalShares` can never reach exactly zero.',
      prob:['Poisson','Markov'], aave:['V2: Empty market rounding','V2: validateFlashLoan()'], swc:['SWC-101'], confidence:92, lens:'Boundary/periphery' },
    { sev:'HIGH', id:'HIGH-01', title:'Fee-on-transfer token credits more shares than actually received',
      summary:'`deposit()` credits `msg.sender` with the `amount` parameter directly instead of the actual tokens received. For a fee-on-transfer token, `received = amount - fee`, so every deposit mints unbacked shares proportional to the fee rate.',
      rootCause:'`deposit(uint256 amount)` calls `shares[msg.sender] += amount` using the caller-supplied `amount` rather than a balance-delta measured via `token.balanceOf(address(this))` before/after the transfer.',
      symmetry:'`withdraw()` correctly pays out based on the pool\'s live token balance, but `deposit()` credits the pre-fee amount — the two paths are asymmetric: one trusts the input, the other trusts reality.',
      externalPreconditions:'- The deposited token charges a transfer fee (fee-on-transfer behavior).',
      internalPreconditions:'- No allowlist restricting deposits to fee-free tokens.',
      attackPath:'1. Attacker deposits 1,000,000 PAXG (1% transfer fee).\n2. Protocol actually receives 990,000 PAXG but mints shares for the full 1,000,000.\n3. Attacker redeems the full 1,000,000-worth of shares.\n4. The 10,000 PAXG shortfall is paid out of other depositors\' balances.',
      impact:'Repeatable theft proportional to `fee_rate × deposit_size`. Every existing depositor bears a pro-rata loss on each fee-on-transfer deposit.',
      poc:'```solidity\nfunction test_feeOnTransferShareInflation() public {\n    uint256 before = feeToken.balanceOf(address(pool));\n    vm.prank(attacker);\n    pool.deposit(1_000_000e18); // 1% fee token\n\n    uint256 received = feeToken.balanceOf(address(pool)) - before;\n    assertEq(received, 990_000e18);\n    assertEq(pool.shares(attacker), 1_000_000e18); // minted on pre-fee amount\n}\n```\nExpected log output:\n```\n[PASS] test_feeOnTransferShareInflation() — shares(attacker) = 1000000e18, actual received = 990000e18\n```',
      mitigation:'Measure `received = token.balanceOf(address(this)) - balanceBefore` around the `transferFrom` call and mint shares against `received`, not the caller-supplied `amount`.',
      prob:['Bayesian','Beta'], aave:['V2: validateDeposit','V3: Supply operations'], swc:['SWC-104'], confidence:88, lens:'Asymmetry' },
    { sev:'HIGH', id:'HIGH-02', title:'Read-only reentrancy via Balancer callback inflates borrow power',
      summary:'`getPrice()` reads Balancer pool `totalSupply()` during a `_beforeTokenTransfer` hook, before the Vault\'s token balances are updated for the same operation. `borrow()` is missing `nonReentrant`, so a reentrant call during the callback observes a stale, inflated price.',
      rootCause:'`borrow()` has no reentrancy guard, and `getPrice()` combines `vault.getPoolTokens()` with `pool.totalSupply()` under the unstated assumption that both reads reflect the same pool state snapshot.',
      externalPreconditions:'- The priced asset is a Balancer LP token (or any pool with a documented read-only reentrancy surface).',
      internalPreconditions:'- `borrow()` lacks `nonReentrant` and does not check `vault.getPoolTokens` context.',
      attackPath:'1. Attacker flash-borrows and calls `deposit()`.\n2. Balancer triggers the `_beforeTokenTransfer` hook mid-operation.\n3. From inside the callback, attacker reenters and calls `borrow()`.\n4. `getPrice()` reads a stale `totalSupply()` against not-yet-updated balances, computing an inflated collateral value.\n5. Attacker borrows up to 2x their real collateral value.',
      impact:'Attacker borrows up to 2x their real collateral. Every asset priced through the same Balancer-backed oracle is affected.',
      poc:'```solidity\nfunction test_readOnlyReentrancyInflatesBorrow() public {\n    vm.startPrank(attacker);\n    balancerPool.joinPoolWithReentrantCallback(address(this)); // triggers receive()\n    // inside receive(): pool.borrow(inflatedAmount)\n    vm.stopPrank();\n\n    assertGt(pool.debtOf(attacker), pool.collateralValue(attacker));\n}\n```\nExpected log output:\n```\n[PASS] test_readOnlyReentrancyInflatesBorrow() — debtOf = 2.00x collateralValue\n```',
      mitigation:'Add `nonReentrant` to `borrow()`, and call `vault.manageUserBalance` / `ensureNotInVaultContext()`-style guards before consuming Balancer-derived prices, per Balancer\'s documented mitigation.',
      prob:['Markov','Exponential'], aave:['V2: CEI pattern','V3: Oracle Sentinel'], swc:['SWC-107'], confidence:90, lens:'Reentrancy (periphery × execution trace)' },
    { sev:'MEDIUM', id:'MED-01', title:'Chainlink staleness check missing on price feed',
      summary:'`getPriceUSD()` calls `latestRoundData()` but never validates `updatedAt` against a heartbeat, so the protocol will silently accept a price that is hours old during an oracle node outage.',
      rootCause:'`getPriceUSD()` discards the `updatedAt` return value from `latestRoundData()` instead of checking `block.timestamp - updatedAt <= HEARTBEAT`.',
      externalPreconditions:'- The Chainlink node/aggregator for this feed is offline or delayed beyond its normal heartbeat.',
      internalPreconditions:'- None beyond the missing staleness check itself.',
      attackPath:'1. Chainlink node goes offline.\n2. `latestRoundData()` continues returning a T-4h price.\n3. Protocol proceeds using the stale price for borrow/liquidation decisions.\n4. No concurrent large market move observed in this scan — impact is conditional on price drift during the stale window, kept at Medium without an active exploit path.',
      impact:'Protocol accepts hours-old prices during oracle downtime. Becomes exploitable the moment real price diverges materially from the stale reading.',
      poc:'```solidity\nfunction test_staleOracleAccepted() public {\n    mockFeed.setUpdatedAt(block.timestamp - 4 hours);\n    uint256 price = oracle.getPriceUSD(asset);\n    assertGt(price, 0); // accepted without a staleness revert\n}\n```\nExpected log output:\n```\n[PASS] test_staleOracleAccepted() — price accepted with updatedAt = now - 4h\n```',
      mitigation:'`require(block.timestamp - updatedAt <= HEARTBEAT, "Stale price")` with a heartbeat matched to the feed (e.g. 3600s for ETH/USD).',
      prob:['Exponential','Bayesian'], aave:['V2: Oracle safety','V3: Oracle Sentinel'], swc:['SWC-116'], confidence:75, lens:'Periphery/libraries' },
  ],
  dex: [
    { sev:'CRITICAL', id:'CRIT-01', title:'K-invariant violation via dust swap precision loss',
      summary:'`swap()` computes `amountOut = amountIn * reserve1 / reserve0`. For `amountIn = 1 wei`, the division floors to 0, but the function still updates reserves as if a real swap occurred — silently violating the `x*y=k` invariant on every call.',
      rootCause:'`swap()` never validates `amountOut > 0` before committing the reserve update, so a floored-to-zero output still mutates state.',
      externalPreconditions:'- None; any caller can trigger this with a plain transaction.',
      internalPreconditions:'- Pool reserves large enough that `1 * reserve1 / reserve0` floors to 0 for `amountIn = 1`.',
      attackPath:'1. Attacker calls `swap(tokenA, tokenB, 1 wei)`.\n2. `amountOut` floors to 0 via integer division.\n3. Protocol updates reserves as though the swap completed.\n4. `k = reserve0 * reserve1` silently decreases with each call.\n5. Attacker loops the call ~1e6 times, asymmetrically draining reserves.',
      impact:'Systematic drain of pool reserves via repeated dust swaps. All LP liquidity in the pool is at risk.',
      poc:'```solidity\nfunction test_dustSwapViolatesKInvariant() public {\n    uint256 kBefore = pool.reserve0() * pool.reserve1();\n    for (uint i; i < 1000; i++) {\n        pool.swap(tokenA, tokenB, 1); // 1 wei in, 0 out\n    }\n    uint256 kAfter = pool.reserve0() * pool.reserve1();\n    assertLt(kAfter, kBefore); // invariant violated\n}\n```\nExpected log output:\n```\n[PASS] test_dustSwapViolatesKInvariant() — k decreased from 1.000000e24 to 9.994e23\n```',
      mitigation:'`require(amountOut > 0, "Insufficient output")` before updating reserves. Enforce a `minAmountIn` floor and always multiply before dividing.',
      prob:['Normal','Beta'], aave:['V2: Dust handling'], swc:['SWC-101'], confidence:85, lens:'Math/precision' },
    { sev:'HIGH', id:'HIGH-01', title:'No slippage protection — every swap is sandwichable',
      summary:'`swap()` hardcodes `minAmountOut = 0` with no deadline parameter. Any pending swap can be frontrun to inflate price, forced through at a worse rate, then backrun for risk-free MEV profit.',
      rootCause:'`swap()` accepts no `minAmountOut` or `deadline` argument, so the caller has no way to bound acceptable execution price or expiry.',
      externalPreconditions:'- A rational MEV searcher is monitoring the mempool for this pool.',
      internalPreconditions:'- None; the missing parameters affect every swap unconditionally.',
      attackPath:'1. User submits a swap of 100 ETH → USDC.\n2. MEV bot frontruns: buys USDC first, moving price ~30%.\n3. User\'s swap executes at the inflated price.\n4. MEV bot backruns: sells USDC back for profit.',
      impact:'Every swap through this pool is vulnerable. Game-theoretically, rational MEV bots exploit it whenever expected profit exceeds gas cost — which is nearly always at meaningful trade sizes.',
      poc:'```solidity\nfunction test_swapSandwichable() public {\n    uint256 quoteBefore = pool.getAmountOut(100e18, tokenIn, tokenOut);\n    vm.prank(mevBot); pool.swap(tokenIn, tokenOut, 500e18); // frontrun\n    vm.prank(user);   pool.swap(tokenIn, tokenOut, 100e18); // victim swap\n    uint256 received = tokenOut.balanceOf(user);\n    assertLt(received, quoteBefore * 80 / 100); // >20% worse than quoted\n}\n```\nExpected log output:\n```\n[PASS] test_swapSandwichable() — received 68.2 USDC vs quoted 98.4 USDC (-30.7%)\n```',
      mitigation:'Add a `minAmountOut` parameter with `require(amountOut >= minAmountOut)`, and a `deadline` parameter with `require(block.timestamp <= deadline)`.',
      prob:['Game Theory','Queueing Theory'], aave:['V2: Slippage protection'], swc:['SWC-114'], confidence:95, lens:'Trust gap (access × economics)' },
  ],
  bridge: [
    { sev:'CRITICAL', id:'CRIT-01', title:'Multi-sig threshold breachable under a binomial key-compromise model',
      summary:'The bridge trusts a 5-of-9 multisig of hot-wallet-held keys to authorize cross-chain mint messages. Under a binomial compromise model (`p=0.25` per key annually), `P(5+ of 9 compromised) ≈ 8.7%` — a forged threshold-signed message mints unbacked tokens on the destination chain.',
      rootCause:'`mintUnbacked()`-equivalent bridge logic accepts any message carrying 5 valid signatures from the 9-key set, with no additional on-chain economic bound or delay on large mints.',
      externalPreconditions:'- Attacker compromises at least 5 of the 9 validator hot-wallet keys (via phishing, infra compromise, or key-leak).',
      internalPreconditions:'- No time-delay or value cap on cross-chain mint messages regardless of signature count.',
      attackPath:'1. Attacker compromises 5 of 9 validator keys.\n2. Attacker forges a message: "mint 10M USDC on destination chain".\n3. The 5-of-9 threshold is satisfied; the message executes.\n4. 10M USDC is minted on the destination chain with no real backing on the source chain.',
      impact:'Total bridge TVL is at risk. The binomial model puts annual compromise probability at ~8.7% given the stated per-key compromise rate.',
      poc:'```solidity\nfunction test_forgedThresholdMessageMints() public {\n    bytes memory msg_ = abi.encode(destChain, attacker, 10_000_000e6);\n    bytes[] memory sigs = signWithCompromisedKeys(msg_, 5); // 5 of 9\n\n    bridge.executeMessage(msg_, sigs);\n    assertEq(usdc.balanceOf(attacker), 10_000_000e6); // minted with no backing\n}\n```\nExpected log output:\n```\n[PASS] test_forgedThresholdMessageMints() — balanceOf(attacker) = 10000000000000 (10M USDC, 6 decimals)\n```',
      mitigation:'Move validator keys to HSMs or MPC-TSS custody, require hardware attestation per signature, and add a 24h time-delay with an emergency-pause window on large-value transfers.',
      prob:['Binomial','Weibull'], aave:['V3: Bridge role (BRIDGE can mintUnbacked)'], swc:['SWC-109'], confidence:80, lens:'Access control' },
  ],
}

export const CHAINLIGHT_INSIGHTS = [
  { icon:'💥', title:'Access control bypasses (28% of losses)', year:'2024',
    body:'Most high-value exploits exploited misconfigured role permissions — BRIDGE, RISK_ADMIN, POOL_ADMIN equivalents. Attacker gained RISK_ADMIN to atomically set LT→0 then liquidate all positions.',
    tags:['access-control','role-escalation','Aave-threat-model'] },
  { icon:'📉', title:'Oracle manipulation via flash loans (24%)', year:'2024',
    body:'Log-Normal tails: 3σ price drops with 1-3 block oracle lag create liquidation windows. 6 protocols using slot0 Uniswap price as oracle — all exploited via sandwich.',
    tags:['oracle','flash-loan','slot0','MEV','log-normal'] },
  { icon:'🔄', title:'Reentrancy via callbacks (19%)', year:'2024',
    body:'Read-only reentrancy remains underdetected. View functions reading Balancer/Curve state during callbacks were exploited to inflate collateral value, bypassing HF checks.',
    tags:['reentrancy','ERC-777','read-only','Balancer'] },
  { icon:'⛓️', title:'Cross-chain bridge logic flaws (17%)', year:'2024',
    body:'Binomial model: 5 validators at p=0.2 → P(3+ compromised)=20.5%. Seven bridge exploits involved validator key extraction rather than smart contract bugs.',
    tags:['bridge','multi-sig','binomial','validator'] },
  { icon:'♟️', title:'Governance / token economic attacks (9%)', year:'2024',
    body:'Game theory: Nash equilibrium showed 3 protocols where quorum attainable with 12% supply via flash-borrowed governance tokens. Pareto distribution of holders made this feasible.',
    tags:['governance','flash-loan','game-theory','quorum','Pareto'] },
  { icon:'🔢', title:'Precision loss in invariant math (3%)', year:'2024',
    body:'Division-before-multiply in interest accrual and share pricing. Beta distribution: utilization→1.0 causes 1 wei rounding exploitable via share inflation on empty markets.',
    tags:['precision','arithmetic','SWC-101','share-inflation','Beta'] },
]

export const SEV_COLORS: Record<string, string> = {
  CRITICAL: 'bg-red-900/40 text-red-300 border border-red-800/60',
  HIGH:     'bg-orange-900/40 text-orange-300 border border-orange-800/60',
  MEDIUM:   'bg-yellow-900/40 text-yellow-300 border border-yellow-800/60',
  LOW:      'bg-blue-900/40 text-blue-300 border border-blue-800/60',
  INFO:     'bg-gray-800/60 text-gray-400 border border-gray-700/60',
}
