import type { Finding, Lead, SoloditRef } from './data'

export interface ExportPayload {
  filename: string
  findings: Finding[]
  leads: Lead[]
  soloditRefs: SoloditRef[]
  timestamp?: number
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  URL.revokeObjectURL(url)
}

function safeStem(filename: string) {
  return (filename || 'audit-report').replace(/[^a-z0-9-_]+/gi, '_').slice(0, 60)
}

// ── Markdown ────────────────────────────────────────────────────────────────

function findingToMarkdown(f: Finding, i: number): string {
  const lines: string[] = []
  lines.push(`## ${i + 1}. [${f.sev}] ${f.title}`)
  if (typeof f.confidence === 'number') lines.push(`*Confidence: ${f.confidence}%*`)
  lines.push('')
  lines.push('### Summary')
  lines.push(f.summary || '')
  lines.push('')
  lines.push('### Root Cause')
  lines.push(f.rootCause || '')
  lines.push('')
  if (f.symmetry) {
    lines.push('### Symmetry')
    lines.push(f.symmetry)
    lines.push('')
  }
  lines.push('### External Pre-conditions')
  lines.push(f.externalPreconditions || '- None')
  lines.push('')
  lines.push('### Internal Pre-conditions')
  lines.push(f.internalPreconditions || '- None')
  lines.push('')
  lines.push('### Attack Path')
  lines.push(f.attackPath || '')
  lines.push('')
  lines.push('### Impact')
  lines.push(f.impact || '')
  lines.push('')
  lines.push('### Proof of Concept')
  lines.push(f.poc || '')
  lines.push('')
  lines.push('### Mitigation')
  lines.push(f.mitigation || '')
  if (f.lens || (f.prob && f.prob.length) || (f.aave && f.aave.length) || (f.swc && f.swc.length) || (f.immunefi && f.immunefi.length)) {
    lines.push('')
    lines.push('### Tags')
    const tags = [f.lens, ...(f.prob || []), ...(f.aave || []), ...(f.swc || []), ...(f.immunefi || [])].filter(Boolean)
    lines.push(tags.join(', '))
  }
  return lines.join('\n')
}

export function buildMarkdownReport(payload: ExportPayload): string {
  const { filename, findings, leads, soloditRefs, timestamp } = payload
  const date = new Date(timestamp || Date.now()).toISOString()
  const lines: string[] = []
  lines.push(`# OTISEC SENTINEL — Audit Report`)
  lines.push('')
  lines.push(`**File(s):** ${filename}`)
  lines.push(`**Generated:** ${date}`)
  lines.push(`**Findings:** ${findings.length}`)
  lines.push('')
  lines.push('---')
  lines.push('')
  findings.forEach((f, i) => {
    lines.push(findingToMarkdown(f, i))
    lines.push('')
    lines.push('---')
    lines.push('')
  })
  if (leads.length > 0) {
    lines.push('## Leads for Manual Review')
    lines.push('')
    leads.forEach(l => {
      lines.push(`- **${l.title}** — ${l.codeSmells} — ${l.description}`)
    })
    lines.push('')
  }
  if (soloditRefs.length > 0) {
    lines.push('## Real-World Precedent (Solodit)')
    lines.push('')
    soloditRefs.forEach(r => {
      lines.push(`- [${r.severity}] [${r.title}](${r.sourceLink}) — ${r.firm} audit of ${r.protocol}`)
    })
    lines.push('')
  }
  lines.push('---')
  lines.push('*Generated by OTISEC SENTINEL — AI analysis can never verify the complete absence of vulnerabilities. Team security reviews, bug bounty programs, and on-chain monitoring are strongly recommended.*')
  return lines.join('\n')
}

export function downloadMarkdown(payload: ExportPayload) {
  const md = buildMarkdownReport(payload)
  triggerDownload(new Blob([md], { type: 'text/markdown' }), `${safeStem(payload.filename)}-audit-report.md`)
}

// ── PDF (jsPDF, plain-text layout with pagination) ─────────────────────────

export async function downloadPdf(payload: ExportPayload) {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 48
  const maxWidth = pageWidth - margin * 2
  let y = margin

  const ensureSpace = (needed: number) => {
    if (y + needed > pageHeight - margin) {
      doc.addPage()
      y = margin
    }
  }

  const writeHeading = (text: string, size: number, gapAfter = 10) => {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(size)
    const wrapped = doc.splitTextToSize(text, maxWidth)
    ensureSpace(wrapped.length * (size + 4) + gapAfter)
    doc.text(wrapped, margin, y)
    y += wrapped.length * (size + 4) + gapAfter
  }

  const writeBody = (text: string, gapAfter = 10) => {
    if (!text) return
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9.5)
    const wrapped = doc.splitTextToSize(text.replace(/[`*_#]/g, ''), maxWidth)
    for (const line of wrapped) {
      ensureSpace(13)
      doc.text(line, margin, y)
      y += 13
    }
    y += gapAfter
  }

  writeHeading('OTISEC SENTINEL — Audit Report', 16, 4)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.text(`File(s): ${payload.filename}`, margin, y); y += 13
  doc.text(`Generated: ${new Date(payload.timestamp || Date.now()).toLocaleString()}`, margin, y); y += 13
  doc.text(`Findings: ${payload.findings.length}`, margin, y); y += 20

  payload.findings.forEach((f, i) => {
    ensureSpace(30)
    writeHeading(`${i + 1}. [${f.sev}] ${f.title}`, 12.5, 6)
    if (typeof f.confidence === 'number') writeBody(`Confidence: ${f.confidence}%`, 6)

    writeHeading('Summary', 10, 3); writeBody(f.summary)
    writeHeading('Root Cause', 10, 3); writeBody(f.rootCause)
    if (f.symmetry) { writeHeading('Symmetry', 10, 3); writeBody(f.symmetry) }
    writeHeading('External Pre-conditions', 10, 3); writeBody(f.externalPreconditions || 'None')
    writeHeading('Internal Pre-conditions', 10, 3); writeBody(f.internalPreconditions || 'None')
    writeHeading('Attack Path', 10, 3); writeBody(f.attackPath)
    writeHeading('Impact', 10, 3); writeBody(f.impact)
    writeHeading('Proof of Concept', 10, 3); writeBody(f.poc)
    writeHeading('Mitigation', 10, 3); writeBody(f.mitigation, 16)
  })

  if (payload.leads.length > 0) {
    writeHeading('Leads for Manual Review', 13, 8)
    payload.leads.forEach(l => writeBody(`• ${l.title} — ${l.codeSmells} — ${l.description}`, 4))
  }

  if (payload.soloditRefs.length > 0) {
    writeHeading('Real-World Precedent (Solodit)', 13, 8)
    payload.soloditRefs.forEach(r => writeBody(`• [${r.severity}] ${r.title} — ${r.firm} audit of ${r.protocol}`, 4))
  }

  doc.save(`${safeStem(payload.filename)}-audit-report.pdf`)
}

// ── DOCX (docx package) ─────────────────────────────────────────────────────

export async function downloadDocx(payload: ExportPayload) {
  const { Document, Packer, Paragraph, HeadingLevel, TextRun } = await import('docx')

  const section = (label: string, content: string) => ([
    new Paragraph({ text: label, heading: HeadingLevel.HEADING_3, spacing: { before: 160, after: 60 } }),
    new Paragraph({ children: [new TextRun(content || 'None')], spacing: { after: 80 } }),
  ])

  const children = [
    new Paragraph({ text: 'OTISEC SENTINEL — Audit Report', heading: HeadingLevel.TITLE }),
    new Paragraph({ text: `File(s): ${payload.filename}`, spacing: { after: 40 } }),
    new Paragraph({ text: `Generated: ${new Date(payload.timestamp || Date.now()).toLocaleString()}`, spacing: { after: 40 } }),
    new Paragraph({ text: `Findings: ${payload.findings.length}`, spacing: { after: 200 } }),
  ]

  payload.findings.forEach((f, i) => {
    children.push(new Paragraph({
      text: `${i + 1}. [${f.sev}] ${f.title}`,
      heading: HeadingLevel.HEADING_1,
      spacing: { before: 300, after: 40 },
    }))
    if (typeof f.confidence === 'number') {
      children.push(new Paragraph({ children: [new TextRun({ text: `Confidence: ${f.confidence}%`, italics: true })], spacing: { after: 80 } }))
    }
    children.push(...section('Summary', f.summary))
    children.push(...section('Root Cause', f.rootCause))
    if (f.symmetry) children.push(...section('Symmetry', f.symmetry))
    children.push(...section('External Pre-conditions', f.externalPreconditions))
    children.push(...section('Internal Pre-conditions', f.internalPreconditions))
    children.push(...section('Attack Path', f.attackPath))
    children.push(...section('Impact', f.impact))
    children.push(...section('Proof of Concept', f.poc))
    children.push(...section('Mitigation', f.mitigation))
  })

  if (payload.leads.length > 0) {
    children.push(new Paragraph({ text: 'Leads for Manual Review', heading: HeadingLevel.HEADING_1, spacing: { before: 300, after: 80 } }))
    payload.leads.forEach(l => {
      children.push(new Paragraph({ text: `${l.title} — ${l.codeSmells} — ${l.description}`, bullet: { level: 0 } }))
    })
  }

  if (payload.soloditRefs.length > 0) {
    children.push(new Paragraph({ text: 'Real-World Precedent (Solodit)', heading: HeadingLevel.HEADING_1, spacing: { before: 300, after: 80 } }))
    payload.soloditRefs.forEach(r => {
      children.push(new Paragraph({ text: `[${r.severity}] ${r.title} — ${r.firm} audit of ${r.protocol}`, bullet: { level: 0 } }))
    })
  }

  const doc = new Document({ sections: [{ children }] })
  const blob = await Packer.toBlob(doc)
  triggerDownload(blob, `${safeStem(payload.filename)}-audit-report.docx`)
}
