// Curated, real-world bug-bounty precedent, distilled from:
// https://github.com/sayan011/Immunefi-bug-bounty-writeups-list
//
// Each entry is a paid (or credibly disclosed) real vulnerability with a code-pattern
// signature the audit engine can match against uploaded contracts — the same role
// Solodit corroboration plays (see searchSolodit in api.audit.ts), but sourced from
// whitehat bounty writeups instead of audit-contest reports. Corroboration only:
// a keyword match is a lead to chase with the 12-lens sweep, never an automatic finding.

export interface ImmunefiCase {
  protocol: string
  bounty: string
  severity: string
  category: string
  pattern: string
  url: string
  keywords: RegExp[]
}

export const IMMUNEFI_CASES: ImmunefiCase[] = [
  { protocol: 'Wormhole', bounty: '$10M', severity: 'Critical', category: 'Uninitialized proxy',
    pattern: 'Upgradeable proxy left uninitialized post-deploy; attacker calls initialize() directly and seizes a privileged role.',
    url: 'https://medium.com/immunefi/wormhole-uninitialized-proxy-bugfix-review-90250c41a43a',
    keywords: [/initialize\(/i, /Initializable/i, /_disableInitializers/i, /proxy/i] },
  { protocol: '88mph', bounty: '$42K', severity: 'Critical', category: 'Uninitialized proxy',
    pattern: 'Initializer function callable more than once / by anyone post-deploy, letting an attacker re-init privileged state.',
    url: 'https://medium.com/immunefi/88mph-function-initialization-bug-fix-postmortem-c3a2282894d3',
    keywords: [/initialize\(/i, /Initializable/i] },
  { protocol: 'Aurora', bounty: '$6M', severity: 'Critical', category: 'Infinite mint / spend',
    pattern: 'Accounting bug let an attacker spend/withdraw funds without a corresponding balance decrement.',
    url: 'https://medium.com/immunefi/aurora-infinite-spend-bugfix-review-6m-payout-e635d24273d',
    keywords: [/balances?\[.*\]\s*-=/i, /unchecked\s*{/i] },
  { protocol: 'Optimism', bounty: '$2M', severity: 'Critical', category: 'Infinite mint / spend',
    pattern: 'Bridge deposit/mint path allowed duplicated minting of the same deposit — money duplication across L1/L2.',
    url: 'https://medium.com/immunefi/optimism-infinite-money-duplication-bugfix-review-daa6597146a0',
    keywords: [/mint\(/i, /bridge/i, /deposit\(/i, /nonce/i] },
  { protocol: 'Bitswift', bounty: '$4.5K', severity: 'Critical', category: 'Infinite mint / spend',
    pattern: 'Unrestricted mint() reachable by a non-privileged caller.',
    url: 'https://medium.com/immunefi/bitswift-unlimited-mint-bugfix-postmortem-147a1e57dca9',
    keywords: [/function\s+mint\(/i] },
  { protocol: 'Belt Finance', bounty: '$1.05M', severity: 'Critical', category: 'Logic error',
    pattern: 'Strategy accounting logic error let an attacker mint disproportionate shares relative to deposited value.',
    url: 'https://medium.com/immunefi/belt-finance-logic-error-bug-fix-postmortem-39308a158291',
    keywords: [/totalShares|totalSupply/i, /deposit\(/i, /convertToShares/i] },
  { protocol: 'Beanstalk', bounty: '$182K', severity: 'Critical', category: 'Logic error',
    pattern: 'Logic error in a settlement/convert path let an attacker extract more value than deposited.',
    url: 'https://medium.com/immunefi/beanstalk-logic-error-bugfix-review-4fea17478716',
    keywords: [/convert\(/i, /silo/i] },
  { protocol: 'Beanstalk', bounty: '$1.1M', severity: 'Critical', category: 'Insufficient input validation',
    pattern: 'Missing validation on a user-supplied array/index let an attacker reference unintended state.',
    url: 'https://medium.com/immunefi/beanstalk-insufficient-input-validation-bugfix-review-fc3fdbaab15b',
    keywords: [/\[\s*msg\.sender\s*\]/i, /calldata\s*\[/i, /uint256\[\]\s+calldata/i] },
  { protocol: 'Port Finance', bounty: '$630K', severity: 'Critical', category: 'Logic error',
    pattern: 'Collateral/liability logic error allowed extraction beyond legitimate entitlement.',
    url: 'https://medium.com/immunefi/port-finance-logic-error-bugfix-review-29767aced446',
    keywords: [/collateral/i, /liquidat/i] },
  { protocol: 'Mushrooms Finance', bounty: '$60K', severity: 'Critical', category: 'Logic error',
    pattern: 'Vault share logic error allowed value extraction disproportionate to deposit.',
    url: 'https://medium.com/immunefi/mushrooms-finance-logic-error-bug-fix-postmortem-780122821621',
    keywords: [/totalShares|totalSupply/i, /vault/i] },
  { protocol: 'Tidal Finance', bounty: '$25K', severity: 'Critical', category: 'Logic error',
    pattern: 'Premium/payout accounting logic error.',
    url: 'https://medium.com/immunefi/tidal-finance-logic-error-bug-fix-postmortem-3607d8b7ed1f',
    keywords: [/premium/i, /payout/i] },
  { protocol: 'Yield Protocol', bounty: '$95K', severity: 'Critical', category: 'Logic error',
    pattern: 'Fixed-yield settlement logic error.',
    url: 'https://medium.com/immunefi/yield-protocol-logic-error-bugfix-review-7b86741e6f50',
    keywords: [/redeem\(/i, /maturity/i] },
  { protocol: 'Synthetix', bounty: '$150K', severity: 'Critical', category: 'Logic error',
    pattern: 'Debt/settlement logic error in a synth exchange path.',
    url: 'https://medium.com/immunefi/synthetix-logic-error-bugfix-review-40da0ead5f4f',
    keywords: [/debt/i, /exchange\(/i] },
  { protocol: 'Fei Protocol', bounty: '$800K', severity: 'Critical', category: 'Flash loan',
    pattern: 'Flash-loan-atomic manipulation of an internal price/accounting reference exploited within one tx.',
    url: 'https://medium.com/immunefi/fei-protocol-flashloan-vulnerability-postmortem-7c5dc001affb',
    keywords: [/flash\s*loan|flashLoan/i, /reweight|rebase/i] },
  { protocol: 'marginfi', bounty: 'Disclosed', severity: 'Critical', category: 'Flash loan',
    pattern: 'Flash-loan path let an attacker manipulate collateral valuation atomically before liquidation checks ran.',
    url: 'https://blog.asymmetric.re/threat-contained-marginfi-flash-loan-vulnerability/',
    keywords: [/flash\s*loan|flashLoan/i, /health\s*factor|healthFactor/i] },
  { protocol: 'Sense Finance', bounty: '$50K', severity: 'Critical', category: 'Access control',
    pattern: 'Missing/weak access-control guard on a privileged settlement function.',
    url: 'https://medium.com/immunefi/sense-finance-access-control-issue-bugfix-review-32e0c806b1a0',
    keywords: [/onlyOwner|onlyAdmin|AccessControl/i] },
  { protocol: 'Enzyme Finance', bounty: '$400K', severity: 'Critical', category: 'Missing privilege check',
    pattern: 'A sensitive external-facing function was missing the privilege check present on its sibling function.',
    url: 'https://medium.com/immunefi/enzyme-finance-missing-privilege-check-bugfix-review-ddb5e87b8058',
    keywords: [/function\s+\w+\([^)]*\)\s+external/i] },
  { protocol: 'Alchemix', bounty: '$7.5K', severity: 'High', category: 'Access control',
    pattern: 'Access-control gap on a state-mutating function.',
    url: 'https://medium.com/immunefi/alchemix-access-control-bug-fix-debrief-a13d39b9f2e0',
    keywords: [/onlyOwner|onlyAdmin/i] },
  { protocol: 'Enzyme Finance', bounty: '$19K', severity: 'Critical', category: 'Oracle manipulation',
    pattern: 'Price oracle read was manipulable within a single transaction, mispricing a fund position.',
    url: 'https://medium.com/immunefi/enzyme-finance-price-oracle-manipulation-bug-fix-postmortem-4e1f3d4201b5',
    keywords: [/getPrice|latestRoundData|slot0/i, /oracle/i] },
  { protocol: 'Notional Finance', bounty: '$1.1M', severity: 'Critical', category: 'Double counting',
    pattern: 'Free collateral was double-counted across two accounting paths, allowing over-borrowing.',
    url: 'https://medium.com/immunefi/notional-double-counting-free-collateral-bugfix-review-28b634903934',
    keywords: [/freeCollateral|collateralRatio/i, /borrow\(/i] },
  { protocol: 'APWine', bounty: '$100K', severity: 'Critical', category: 'Delegation check error',
    pattern: 'Delegation/allowance check used the wrong account reference, letting an attacker act on behalf of another user.',
    url: 'https://medium.com/immunefi/apwine-incorrect-check-of-delegations-bugfix-review-7e401a49c04f',
    keywords: [/delegate/i, /allowance\[/i] },
  { protocol: 'DFX Finance', bounty: '$100K', severity: 'Critical', category: 'Rounding error',
    pattern: 'Rounding direction in a curve/swap formula favored the attacker instead of the protocol.',
    url: 'https://medium.com/immunefi/dfx-finance-rounding-error-bugfix-review-17ba5ffb4114',
    keywords: [/\/\s*1e\d+/i, /mulDiv|wadDiv|wadMul/i] },
  { protocol: 'Balancer', bounty: '$1M', severity: 'Critical', category: 'Rounding error',
    pattern: 'Rounding error in pool math allowed systematic value extraction over repeated swaps.',
    url: 'https://medium.com/immunefi/balancer-rounding-error-bugfix-review-cbf69482ee3d',
    keywords: [/mulDiv|wadDiv|wadMul/i, /pool/i] },
  { protocol: 'The Graph', bounty: '$290K', severity: 'High + Critical', category: 'Rounding error',
    pattern: 'Rounding error in a staking/reward calculation compounded across repeated operations.',
    url: 'https://medium.com/immunefi/the-graph-rounding-error-bugfix-review-c946ff470f65',
    keywords: [/stake\(/i, /reward/i] },
  { protocol: 'Zapper', bounty: '$25K', severity: 'Critical', category: 'Arbitrary call',
    pattern: 'User-supplied calldata was forwarded to an arbitrary external target without validation, draining approvals.',
    url: 'https://medium.com/immunefi/zapper-arbitrary-call-data-bug-fix-postmortem-d75a4a076ae9',
    keywords: [/\.call\(/i, /calldata\s+target/i] },
  { protocol: 'xDai', bounty: '$5K', severity: 'Medium', category: 'Arbitrary call',
    pattern: 'Unvalidated target/method for a delegated call allowed an unintended state-mutating action.',
    url: 'https://medium.com/immunefi/xdai-stake-arbitrary-call-method-bug-postmortem-f80a90ac56e3',
    keywords: [/\.call\(/i, /delegatecall/i] },
  { protocol: 'O3 Swap', bounty: '$500', severity: 'Critical', category: 'Reentrancy',
    pattern: 'ERC-777 hook re-entered an unprotected swap function before settlement finalized.',
    url: 'https://medium.com/@Heuss/unprotected-swap-function-a-erc777-reentrancy-vulnerability-81aaeaa75a2a',
    keywords: [/tokensReceived|_beforeTokenTransfer/i, /swap\(/i] },
  { protocol: 'Polygon', bounty: '$75K', severity: 'High', category: 'Consensus bypass',
    pattern: 'Validation gap allowed bypassing the intended consensus/quorum check.',
    url: 'https://medium.com/immunefi/polygon-consensus-bypass-bugfix-review-7076ce5047fe',
    keywords: [/quorum|threshold/i, /validator/i] },
  { protocol: 'Optimism', bounty: '$20K', severity: 'Critical', category: 'Censorship / DoS',
    pattern: 'A privileged sequencer/operator path could be starved or censored, denying service.',
    url: 'https://www.iosiro.com/blog/optimism-censorship-bug-disclosure',
    keywords: [/sequencer/i, /onlyOperator/i] },
  { protocol: 'Stacks', bounty: '~$76K', severity: 'Critical', category: 'Denial of service',
    pattern: 'Unbounded loop / unchecked failure path allowed a single attacker to lock a shared resource for everyone.',
    url: 'https://medium.com/immunefi/stacks-dos-bugfix-review-dc0f2a75b276',
    keywords: [/for\s*\(/i, /while\s*\(/i] },
  { protocol: 'zkSync', bounty: '$200K', severity: 'Critical', category: 'Insufficient proof verification',
    pattern: 'A ZK proof/verification path accepted an insufficiently validated proof.',
    url: 'https://medium.com/immunefi/zksync-insufficient-proof-verification-bugfix-review-dcd57944d0e2',
    keywords: [/verifyProof|verify\(/i] },
  { protocol: 'Raydium', bounty: '$505K', severity: 'Critical', category: 'Tick / price manipulation',
    pattern: 'Concentrated-liquidity tick math could be manipulated to misprice a position.',
    url: 'https://medium.com/immunefi/raydium-tick-manipulation-bugfix-review-c6aae4527ed6',
    keywords: [/tick/i, /sqrtPrice/i] },
  { protocol: 'RAI', bounty: 'Disclosed (would be $0)', severity: 'Critical', category: 'Return-data bombing',
    pattern: 'Liquidation engine trusted the size of returned calldata from an external call, allowing a griefing DoS via an oversized return payload.',
    url: 'https://www.trust-security.xyz/post/returndata-bombing-rai-s-liquidation-engine-a-critical-bug-worth-0',
    keywords: [/\.call\(/i, /returndatasize|returndatacopy/i] },
  { protocol: 'Scroll', bounty: '$1M', severity: 'Critical', category: 'Message spoofing',
    pattern: 'Cross-chain bridge message verification gap allowed a spoofed message to be accepted as legitimate.',
    url: 'https://forum.scroll.io/t/report-scroll-mainnet-emergency-upgrade-on-2025-04-25/666',
    keywords: [/bridge/i, /relayMessage|xDomainMessage/i] },
  { protocol: 'Compound (Trust Security)', bounty: 'Not paid (known issue)', severity: 'Critical', category: 'Liquidation seizure',
    pattern: 'Liquidators could seize collateral assets the borrower never actually held.',
    url: 'https://www.trust-security.xyz/post/crit-compound-liquidators-may-seize-assets-not-held-as-collateral-closed-as-known-issue',
    keywords: [/seize\(/i, /liquidat/i] },
  { protocol: 'LayerZero / Stargate (Trust Security)', bounty: '$5K / Not paid', severity: 'High / Low', category: 'Cross-chain trust assumption',
    pattern: 'Cross-chain messaging trusted an unvalidated relayer/oracle combination, breaking the intended trust model.',
    url: 'https://www.trust-security.xyz/post/learning-by-breaking-a-layerzero-case-study-part-2',
    keywords: [/lzReceive|relayer|ultraLightNode/i] },
]

// Same keyword-detection technique as Solodit's extractKeywords() in api.audit.ts —
// heuristically match code patterns to real bounty precedent instead of a live search API.
export function matchImmunefiCases(code: string, max = 5): ImmunefiCase[] {
  const scored = IMMUNEFI_CASES
    .map((c) => ({ c, hits: c.keywords.filter((re) => re.test(code)).length }))
    .filter((x) => x.hits > 0)
    .sort((a, b) => b.hits - a.hits)
  return scored.slice(0, max).map((x) => x.c)
}
